# Generated by Django 4.0.5 on 2022-06-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatelogRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('PhoneNumber', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('CompanyName', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Application', models.CharField(max_length=255)),
                ('Message', models.TextField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
    ]
