# Generated by Django 4.0.5 on 2022-06-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_catelogrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='Message',
            field=models.TextField(default=None, max_length=255),
        ),
    ]
